language: node_js
node_js: lts/*
services:
  - docker
branches:
  only:
    - master
before_install: cd budget-service
install: yarn
before_script: yarn build
script: yarn test
before_deploy: cd ..
deploy:
  provider: script
  script: bash budget-service/script/deploy.sh
  on:
    branch: master
