version: "3"
services:
  web:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    links:
      - frontend
    volumes:
      - ./docker/volumes/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/.env.dev:/app/frontend/.env
      - /app/frontend/node_modules

  budget-service:
    build:
      context: ./budget-service
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./budget-service:/app/budget-service
      - ./budget-service/.env.dev:/app/budget-service/.env
      # - ./docker/volumes/budget-service/.env:/app/budget-service/.env
      - /app/budget-service/node_modules

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=budget
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./docker/volumes/mysql/data:/var/lib/mysql
      - ./docker/volumes/mysql/dump:/docker-entrypoint-initdb.d
